### PR TITLE
Support float celsius values #38

### LINKED ISSUE #38: [bug] [docker-mqtt] Support float values for celsius
Currently, you get an error when trying to set a float.  Will still need to check we only allow x.0 and x.5

```^[2023-06-18 09:47:14,232:INFO:MQTT message received on topic: homie/hot_tub/J335/set_temperature/set with value: 38.5
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/app/docker_mqtt_app.py", line 33, in on_message
    new_temp = int(msg.payload.decode())
               ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '38.5'```

### PR DESCRIPTION
**Pull request by jackbrown1993**

### CODE REVIEW

**Comment by jackbrown1993** [comment]
@dhmsjs do you know how we can allow curseUI to accept a float value in the input for set temp? It currently doesn't allow x.5 for example at the moment. Jacuzzi's set to use celsius allows values increasing in 0.5 steps

**Comment by dhmsjs** [comment]
There are several dialog classes set up already -- EditDialog is the base class and then TextDialog, EnumDialog and ListDialog inherit from that.  I suspect it would mostly just need a small change to support decimal point character entry. Not sure without looking deeper whether it would be best to modify the TextDialog class or create a FloatDialog instead.

**Comment by dhmsjs** [comment]
Looks like TextDialog supports all ASCII characters, so that isn't the problem. What is the actual error that occurs?

**Comment by jackbrown1993** [comment]
> Looks like TextDialog supports all ASCII characters, so that isn't the problem. What is the actual error that occurs?

It doesn't seem to allow me to input '.' nor does it allow backspace if you make a mistake.

**Comment by dhmsjs** [comment]
I've added a FloatDialog class to cursesui.py to handle editing floating point values. To use it you would replace a current instance of EditDialog with FloatDialog for those variables that take float values.  Works with demoprocess.py at least.

**Comment by jackbrown1993** [comment]
> I've added a FloatDialog class to cursesui.py to handle editing floating point values. To use it you would replace a current instance of EditDialog with FloatDialog for those variables that take float values. Works with demoprocess.py at least.

Thanks @dhmsjs, do you want to submit a pull request on this repo or shall I copy code?

**Comment by dhmsjs** [comment]
From my perspective you can just copy over the code but you are clearly more familiar with using github than I am so if you prefer the pull request just let me know me why.

**Comment by jackbrown1993** [comment]
@dhmsjs thanks will copy it across, not an issue as a small amount od code. For larger changes, its good to open a pull request to the repository you want to contribute towards so you can check that there are no conflicts in the code and it also shows you as the contributor.

**Pull request merged**
